name: Update Language Graph

on:
  push:
    branches:
      - main  # Replace with your default branch name if different
  workflow_dispatch:

jobs:
  update-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download language graph
        run: |
          curl -o language-graph.png "https://ionicabizau.github.io/github-profile-languages/api.html?bableshaazad"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "bableshaazad@outlook.com"
          git config --local user.name "bableshaazad"
          git add language-graph.png
          git commit -m "Update language graph" || echo "No changes to commit"
          git push
